name: Deploy via Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-and-deploy:
    name: Build, Push to Docker Hub, and Deploy
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/custom-static-web:latest

      # Step 4: Connect to the remote server and deploy the new image
      - name: Deploy to Play with Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PWD_HOST }}
          username: ${{ secrets.PWD_USER }}
          key: ${{ secrets.PWD_SSH_KEY }}
          command_timeout: 10m
          debug: true
          script: |
            set -e
            echo "Connection established. Proceeding with deployment."
            
            # Log in to Docker Hub using sudo for necessary permissions
            echo "Authenticating with Docker Hub..."
            echo "${{ secrets.DOCKUP_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # Pull the latest version of the image using sudo
            echo "Pulling latest image..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/custom-static-web:latest
            
            # Stop and remove the old container if it exists, using sudo
            echo "Stopping and removing old container if it exists..."
            sudo docker stop my-site || true
            sudo docker rm my-site || true
            
            # Start a new container with the updated image, using sudo
            echo "Starting new container..."
            sudo docker run -d --name my-site -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/custom-static-web:latest
            
            # Clean up dangling images to save space, using sudo
            echo "Cleaning up old images..."
            sudo docker image prune -af
            
            echo "Deployment successful!"
